#include "CPU6510Impl.h"

// Initialize the opcode table
const std::array<OpcodeInfo, 256> CPU6510Impl::opcodeTable_ = { {

        // 0x00
        {Instruction::BRK, "brk", AddressingMode::Implied, 7, false},
        {Instruction::ORA, "ora", AddressingMode::IndirectX, 6, false},
        {Instruction::KIL, "kil", AddressingMode::Implied, 0, true},
        {Instruction::SLO, "slo", AddressingMode::IndirectX, 8, true},
        {Instruction::NOP, "nop", AddressingMode::ZeroPage, 3, true},
        {Instruction::ORA, "ora", AddressingMode::ZeroPage, 3, false},
        {Instruction::ASL, "asl", AddressingMode::ZeroPage, 5, false},
        {Instruction::SLO, "slo", AddressingMode::ZeroPage, 5, true},
        {Instruction::PHP, "php", AddressingMode::Implied, 3, false},
        {Instruction::ORA, "ora", AddressingMode::Immediate, 2, false},
        {Instruction::ASL, "asl", AddressingMode::Accumulator, 2, false},
        {Instruction::ANC, "anc", AddressingMode::Immediate, 2, true},
        {Instruction::NOP, "nop", AddressingMode::Absolute, 4, true},
        {Instruction::ORA, "ora", AddressingMode::Absolute, 4, false},
        {Instruction::ASL, "asl", AddressingMode::Absolute, 6, false},
        {Instruction::SLO, "slo", AddressingMode::Absolute, 6, true},

        // 0x10
        {Instruction::BPL, "bpl", AddressingMode::Relative, 2, false},
        {Instruction::ORA, "ora", AddressingMode::IndirectY, 5, false},
        {Instruction::KIL, "kil", AddressingMode::Implied, 0, true},
        {Instruction::SLO, "slo", AddressingMode::IndirectY, 8, true},
        {Instruction::NOP, "nop", AddressingMode::ZeroPageX, 4, true},
        {Instruction::ORA, "ora", AddressingMode::ZeroPageX, 4, false},
        {Instruction::ASL, "asl", AddressingMode::ZeroPageX, 6, false},
        {Instruction::SLO, "slo", AddressingMode::ZeroPageX, 6, true},
        {Instruction::CLC, "clc", AddressingMode::Implied, 2, false},
        {Instruction::ORA, "ora", AddressingMode::AbsoluteY, 4, false},
        {Instruction::NOP, "nop", AddressingMode::Implied, 2, true},
        {Instruction::SLO, "slo", AddressingMode::AbsoluteY, 7, true},
        {Instruction::NOP, "nop", AddressingMode::AbsoluteX, 4, true},
        {Instruction::ORA, "ora", AddressingMode::AbsoluteX, 4, false},
        {Instruction::ASL, "asl", AddressingMode::AbsoluteX, 7, false},
        {Instruction::SLO, "slo", AddressingMode::AbsoluteX, 7, true},

        // 0x20
        {Instruction::JSR, "jsr", AddressingMode::Absolute, 6, false},
        {Instruction::AND, "and", AddressingMode::IndirectX, 6, false},
        {Instruction::KIL, "kil", AddressingMode::Implied, 0, true},
        {Instruction::RLA, "rla", AddressingMode::IndirectX, 8, true},
        {Instruction::BIT, "bit", AddressingMode::ZeroPage, 3, false},
        {Instruction::AND, "and", AddressingMode::ZeroPage, 3, false},
        {Instruction::ROL, "rol", AddressingMode::ZeroPage, 5, false},
        {Instruction::RLA, "rla", AddressingMode::ZeroPage, 5, true},
        {Instruction::PLP, "plp", AddressingMode::Implied, 4, false},
        {Instruction::AND, "and", AddressingMode::Immediate, 2, false},
        {Instruction::ROL, "rol", AddressingMode::Accumulator, 2, false},
        {Instruction::ANC, "anc", AddressingMode::Immediate, 2, true},
        {Instruction::BIT, "bit", AddressingMode::Absolute, 4, false},
        {Instruction::AND, "and", AddressingMode::Absolute, 4, false},
        {Instruction::ROL, "rol", AddressingMode::Absolute, 6, false},
        {Instruction::RLA, "rla", AddressingMode::Absolute, 6, true},

        // 0x30
        {Instruction::BMI, "bmi", AddressingMode::Relative, 2, false},
        {Instruction::AND, "and", AddressingMode::IndirectY, 5, false},
        {Instruction::KIL, "kil", AddressingMode::Implied, 0, true},
        {Instruction::RLA, "rla", AddressingMode::IndirectY, 8, true},
        {Instruction::NOP, "nop", AddressingMode::ZeroPageX, 4, true},
        {Instruction::AND, "and", AddressingMode::ZeroPageX, 4, false},
        {Instruction::ROL, "rol", AddressingMode::ZeroPageX, 6, false},
        {Instruction::RLA, "rla", AddressingMode::ZeroPageX, 6, true},
        {Instruction::SEC, "sec", AddressingMode::Implied, 2, false},
        {Instruction::AND, "and", AddressingMode::AbsoluteY, 4, false},
        {Instruction::NOP, "nop", AddressingMode::Implied, 2, true},
        {Instruction::RLA, "rla", AddressingMode::AbsoluteY, 7, true},
        {Instruction::NOP, "nop", AddressingMode::AbsoluteX, 4, true},
        {Instruction::AND, "and", AddressingMode::AbsoluteX, 4, false},
        {Instruction::ROL, "rol", AddressingMode::AbsoluteX, 7, false},
        {Instruction::RLA, "rla", AddressingMode::AbsoluteX, 7, true},

        // 0x40
        {Instruction::RTI, "rti", AddressingMode::Implied, 6, false},
        {Instruction::EOR, "eor", AddressingMode::IndirectX, 6, false},
        {Instruction::KIL, "kil", AddressingMode::Implied, 0, true},
        {Instruction::SRE, "sre", AddressingMode::IndirectX, 8, true},
        {Instruction::NOP, "nop", AddressingMode::ZeroPage, 3, true},
        {Instruction::EOR, "eor", AddressingMode::ZeroPage, 3, false},
        {Instruction::LSR, "lsr", AddressingMode::ZeroPage, 5, false},
        {Instruction::SRE, "sre", AddressingMode::ZeroPage, 5, true},
        {Instruction::PHA, "pha", AddressingMode::Implied, 3, false},
        {Instruction::EOR, "eor", AddressingMode::Immediate, 2, false},
        {Instruction::LSR, "lsr", AddressingMode::Accumulator, 2, false},
        {Instruction::ALR, "alr", AddressingMode::Immediate, 2, true},
        {Instruction::JMP, "jmp", AddressingMode::Absolute, 3, false},
        {Instruction::EOR, "eor", AddressingMode::Absolute, 4, false},
        {Instruction::LSR, "lsr", AddressingMode::Absolute, 6, false},
        {Instruction::SRE, "sre", AddressingMode::Absolute, 6, true},

        // 0x50
        {Instruction::BVC, "bvc", AddressingMode::Relative, 2, false},
        {Instruction::EOR, "eor", AddressingMode::IndirectY, 5, false},
        {Instruction::KIL, "kil", AddressingMode::Implied, 0, true},
        {Instruction::SRE, "sre", AddressingMode::IndirectY, 8, true},
        {Instruction::NOP, "nop", AddressingMode::ZeroPageX, 4, true},
        {Instruction::EOR, "eor", AddressingMode::ZeroPageX, 4, false},
        {Instruction::LSR, "lsr", AddressingMode::ZeroPageX, 6, false},
        {Instruction::SRE, "sre", AddressingMode::ZeroPageX, 6, true},
        {Instruction::CLI, "cli", AddressingMode::Implied, 2, false},
        {Instruction::EOR, "eor", AddressingMode::AbsoluteY, 4, false},
        {Instruction::NOP, "nop", AddressingMode::Implied, 2, true},
        {Instruction::SRE, "sre", AddressingMode::AbsoluteY, 7, true},
        {Instruction::NOP, "nop", AddressingMode::AbsoluteX, 4, true},
        {Instruction::EOR, "eor", AddressingMode::AbsoluteX, 4, false},
        {Instruction::LSR, "lsr", AddressingMode::AbsoluteX, 7, false},
        {Instruction::SRE, "sre", AddressingMode::AbsoluteX, 7, true},

        // 0x60
        {Instruction::RTS, "rts", AddressingMode::Implied, 6, false},
        {Instruction::ADC, "adc", AddressingMode::IndirectX, 6, false},
        {Instruction::KIL, "kil", AddressingMode::Implied, 0, true},
        {Instruction::RRA, "rra", AddressingMode::IndirectX, 8, true},
        {Instruction::NOP, "nop", AddressingMode::ZeroPage, 3, true},
        {Instruction::ADC, "adc", AddressingMode::ZeroPage, 3, false},
        {Instruction::ROR, "ror", AddressingMode::ZeroPage, 5, false},
        {Instruction::RRA, "rra", AddressingMode::ZeroPage, 5, true},
        {Instruction::PLA, "pla", AddressingMode::Implied, 4, false},
        {Instruction::ADC, "adc", AddressingMode::Immediate, 2, false},
        {Instruction::ROR, "ror", AddressingMode::Accumulator, 2, false},
        {Instruction::ARR, "arr", AddressingMode::Immediate, 2, true},
        {Instruction::JMP, "jmp", AddressingMode::Indirect, 5, false},
        {Instruction::ADC, "adc", AddressingMode::Absolute, 4, false},
        {Instruction::ROR, "ror", AddressingMode::Absolute, 6, false},
        {Instruction::RRA, "rra", AddressingMode::Absolute, 6, true},

        // 0x70
        {Instruction::BVS, "bvs", AddressingMode::Relative, 2, false},
        {Instruction::ADC, "adc", AddressingMode::IndirectY, 5, false},
        {Instruction::KIL, "kil", AddressingMode::Implied, 0, true},
        {Instruction::RRA, "rra", AddressingMode::IndirectY, 8, true},
        {Instruction::NOP, "nop", AddressingMode::ZeroPageX, 4, true},
        {Instruction::ADC, "adc", AddressingMode::ZeroPageX, 4, false},
        {Instruction::ROR, "ror", AddressingMode::ZeroPageX, 6, false},
        {Instruction::RRA, "rra", AddressingMode::ZeroPageX, 6, true},
        {Instruction::SEI, "sei", AddressingMode::Implied, 2, false},
        {Instruction::ADC, "adc", AddressingMode::AbsoluteY, 4, false},
        {Instruction::NOP, "nop", AddressingMode::Implied, 2, true},
        {Instruction::RRA, "rra", AddressingMode::AbsoluteY, 7, true},
        {Instruction::NOP, "nop", AddressingMode::AbsoluteX, 4, true},
        {Instruction::ADC, "adc", AddressingMode::AbsoluteX, 4, false},
        {Instruction::ROR, "ror", AddressingMode::AbsoluteX, 7, false},
        {Instruction::RRA, "rra", AddressingMode::AbsoluteX, 7, true},

        // 0x80
        {Instruction::NOP, "nop", AddressingMode::Immediate, 2, true},
        {Instruction::STA, "sta", AddressingMode::IndirectX, 6, false},
        {Instruction::NOP, "nop", AddressingMode::Immediate, 2, true},
        {Instruction::SAX, "sax", AddressingMode::IndirectX, 6, true},
        {Instruction::STY, "sty", AddressingMode::ZeroPage, 3, false},
        {Instruction::STA, "sta", AddressingMode::ZeroPage, 3, false},
        {Instruction::STX, "stx", AddressingMode::ZeroPage, 3, false},
        {Instruction::SAX, "sax", AddressingMode::ZeroPage, 3, true},
        {Instruction::DEY, "dey", AddressingMode::Implied, 2, false},
        {Instruction::NOP, "nop", AddressingMode::Immediate, 2, false},
        {Instruction::TXA, "txa", AddressingMode::Implied, 2, false},
        {Instruction::XAA, "xaa", AddressingMode::Immediate, 2, true},
        {Instruction::STY, "sty", AddressingMode::Absolute, 4, false},
        {Instruction::STA, "sta", AddressingMode::Absolute, 4, false},
        {Instruction::STX, "stx", AddressingMode::Absolute, 4, false},
        {Instruction::SAX, "sax", AddressingMode::Absolute, 4, true},

        // 0x90
        {Instruction::BCC, "bcc", AddressingMode::Relative, 2, false},
        {Instruction::STA, "sta", AddressingMode::IndirectY, 6, false},
        {Instruction::KIL, "kil", AddressingMode::Implied, 0, true},
        {Instruction::AHX, "ahx", AddressingMode::IndirectY, 6, true},
        {Instruction::STY, "sty", AddressingMode::ZeroPageX, 4, false},
        {Instruction::STA, "sta", AddressingMode::ZeroPageX, 4, false},
        {Instruction::STX, "stx", AddressingMode::ZeroPageY, 4, false},
        {Instruction::SAX, "sax", AddressingMode::ZeroPageY, 4, true},
        {Instruction::TYA, "tya", AddressingMode::Implied, 2, false},
        {Instruction::STA, "sta", AddressingMode::AbsoluteY, 5, false},
        {Instruction::TXS, "txs", AddressingMode::Implied, 2, false},
        {Instruction::TAS, "tas", AddressingMode::AbsoluteY, 5, true},
        {Instruction::SHY, "shy", AddressingMode::AbsoluteX, 5, true},
        {Instruction::STA, "sta", AddressingMode::AbsoluteX, 5, false},
        {Instruction::SHX, "shx", AddressingMode::AbsoluteY, 5, true},
        {Instruction::AHX, "ahx", AddressingMode::AbsoluteY, 5, true},

        // 0xA0
        {Instruction::LDY, "ldy", AddressingMode::Immediate, 2, false},
        {Instruction::LDA, "lda", AddressingMode::IndirectX, 6, false},
        {Instruction::LDX, "ldx", AddressingMode::Immediate, 2, false},
        {Instruction::LAX, "lax", AddressingMode::IndirectX, 6, true},
        {Instruction::LDY, "ldy", AddressingMode::ZeroPage, 3, false},
        {Instruction::LDA, "lda", AddressingMode::ZeroPage, 3, false},
        {Instruction::LDX, "ldx", AddressingMode::ZeroPage, 3, false},
        {Instruction::LAX, "lax", AddressingMode::ZeroPage, 3, true},
        {Instruction::TAY, "tay", AddressingMode::Implied, 2, false},
        {Instruction::LDA, "lda", AddressingMode::Immediate, 2, false},
        {Instruction::TAX, "tax", AddressingMode::Implied, 2, false},
        {Instruction::LAX, "lax", AddressingMode::Immediate, 2, true},
        {Instruction::LDY, "ldy", AddressingMode::Absolute, 4, false},
        {Instruction::LDA, "lda", AddressingMode::Absolute, 4, false},
        {Instruction::LDX, "ldx", AddressingMode::Absolute, 4, false},
        {Instruction::LAX, "lax", AddressingMode::Absolute, 4, true},

        // 0xB0
        {Instruction::BCS, "bcs", AddressingMode::Relative, 2, false},
        {Instruction::LDA, "lda", AddressingMode::IndirectY, 5, false},
        {Instruction::KIL, "kil", AddressingMode::Implied, 0, true},
        {Instruction::LAX, "lax", AddressingMode::IndirectY, 5, true},
        {Instruction::LDY, "ldy", AddressingMode::ZeroPageX, 4, false},
        {Instruction::LDA, "lda", AddressingMode::ZeroPageX, 4, false},
        {Instruction::LDX, "ldx", AddressingMode::ZeroPageY, 4, false},
        {Instruction::LAX, "lax", AddressingMode::ZeroPageY, 4, true},
        {Instruction::CLV, "clv", AddressingMode::Implied, 2, false},
        {Instruction::LDA, "lda", AddressingMode::AbsoluteY, 4, false},
        {Instruction::TSX, "tsx", AddressingMode::Implied, 2, false},
        {Instruction::LAS, "las", AddressingMode::AbsoluteY, 4, true},
        {Instruction::LDY, "ldy", AddressingMode::AbsoluteX, 4, false},
        {Instruction::LDA, "lda", AddressingMode::AbsoluteX, 4, false},
        {Instruction::LDX, "ldx", AddressingMode::AbsoluteY, 4, false},
        {Instruction::LAX, "lax", AddressingMode::AbsoluteY, 4, true},

        // 0xC0
        {Instruction::CPY, "cpy", AddressingMode::Immediate, 2, false},
        {Instruction::CMP, "cmp", AddressingMode::IndirectX, 6, false},
        {Instruction::NOP, "nop", AddressingMode::Immediate, 2, true},
        {Instruction::DCP, "dcp", AddressingMode::IndirectX, 8, true},
        {Instruction::CPY, "cpy", AddressingMode::ZeroPage, 3, false},
        {Instruction::CMP, "cmp", AddressingMode::ZeroPage, 3, false},
        {Instruction::DEC, "dec", AddressingMode::ZeroPage, 5, false},
        {Instruction::DCP, "dcp", AddressingMode::ZeroPage, 5, true},
        {Instruction::INY, "iny", AddressingMode::Implied, 2, false},
        {Instruction::CMP, "cmp", AddressingMode::Immediate, 2, false},
        {Instruction::DEX, "dex", AddressingMode::Implied, 2, false},
        {Instruction::AXS, "axs", AddressingMode::Immediate, 2, true},
        {Instruction::CPY, "cpy", AddressingMode::Absolute, 4, false},
        {Instruction::CMP, "cmp", AddressingMode::Absolute, 4, false},
        {Instruction::DEC, "dec", AddressingMode::Absolute, 6, false},
        {Instruction::DCP, "dcp", AddressingMode::Absolute, 6, true},

        // 0xD0
        {Instruction::BNE, "bne", AddressingMode::Relative, 2, false},
        {Instruction::CMP, "cmp", AddressingMode::IndirectY, 5, false},
        {Instruction::KIL, "kil", AddressingMode::Implied, 0, true},
        {Instruction::DCP, "dcp", AddressingMode::IndirectY, 8, true},
        {Instruction::NOP, "nop", AddressingMode::ZeroPageX, 4, true},
        {Instruction::CMP, "cmp", AddressingMode::ZeroPageX, 4, false},
        {Instruction::DEC, "dec", AddressingMode::ZeroPageX, 6, false},
        {Instruction::DCP, "dcp", AddressingMode::ZeroPageX, 6, true},
        {Instruction::CLD, "cld", AddressingMode::Implied, 2, false},
        {Instruction::CMP, "cmp", AddressingMode::AbsoluteY, 4, false},
        {Instruction::NOP, "nop", AddressingMode::Implied, 2, true},
        {Instruction::DCP, "dcp", AddressingMode::AbsoluteY, 7, true},
        {Instruction::NOP, "nop", AddressingMode::AbsoluteX, 4, true},
        {Instruction::CMP, "cmp", AddressingMode::AbsoluteX, 4, false},
        {Instruction::DEC, "dec", AddressingMode::AbsoluteX, 7, false},
        {Instruction::DCP, "dcp", AddressingMode::AbsoluteX, 7, true},

        // 0xE0
        {Instruction::CPX, "cpx", AddressingMode::Immediate, 2, false},
        {Instruction::SBC, "sbc", AddressingMode::IndirectX, 6, false},
        {Instruction::NOP, "nop", AddressingMode::Immediate, 2, true},
        {Instruction::ISC, "isc", AddressingMode::IndirectX, 8, true},
        {Instruction::CPX, "cpx", AddressingMode::ZeroPage, 3, false},
        {Instruction::SBC, "sbc", AddressingMode::ZeroPage, 3, false},
        {Instruction::INC, "inc", AddressingMode::ZeroPage, 5, false},
        {Instruction::ISC, "isc", AddressingMode::ZeroPage, 5, true},
        {Instruction::INX, "inx", AddressingMode::Implied, 2, false},
        {Instruction::SBC, "sbc", AddressingMode::Immediate, 2, false},
        {Instruction::NOP, "nop", AddressingMode::Implied, 2, true},
        {Instruction::SBC, "sbc", AddressingMode::Immediate, 2, true},
        {Instruction::CPX, "cpx", AddressingMode::Absolute, 4, false},
        {Instruction::SBC, "sbc", AddressingMode::Absolute, 4, false},
        {Instruction::INC, "inc", AddressingMode::Absolute, 6, false},
        {Instruction::ISC, "isc", AddressingMode::Absolute, 6, true},

        // 0xF0
        {Instruction::BEQ, "beq", AddressingMode::Relative, 2, false},
        {Instruction::SBC, "sbc", AddressingMode::IndirectY, 5, false},
        {Instruction::KIL, "kil", AddressingMode::Implied, 0, true},
        {Instruction::ISC, "isc", AddressingMode::IndirectY, 8, true},
        {Instruction::NOP, "nop", AddressingMode::ZeroPageX, 4, true},
        {Instruction::SBC, "sbc", AddressingMode::ZeroPageX, 4, false},
        {Instruction::INC, "inc", AddressingMode::ZeroPageX, 6, false},
        {Instruction::ISC, "isc", AddressingMode::ZeroPageX, 6, true},
        {Instruction::SED, "sed", AddressingMode::Implied, 2, false},
        {Instruction::SBC, "sbc", AddressingMode::AbsoluteY, 4, false},
        {Instruction::NOP, "nop", AddressingMode::Implied, 2, true},
        {Instruction::ISC, "isc", AddressingMode::AbsoluteY, 7, true},
        {Instruction::NOP, "nop", AddressingMode::AbsoluteX, 4, true},
        {Instruction::SBC, "sbc", AddressingMode::AbsoluteX, 4, false},
        {Instruction::INC, "inc", AddressingMode::AbsoluteX, 7, false},
        {Instruction::ISC, "isc", AddressingMode::AbsoluteX, 7, true},
} };